name: Deploy Infrastructure to Staging
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./iac
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: gcloud auth configure-docker -q
      - uses: pulumi/actions@v3
        with:
          cloud-url: gs://${{ secrets.GOOGLE_LOGIN_BUCKET }}
          command: up
          stack-name: organization/sapientone/production
          work-dir: ./iac
        env:
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
