name: Deploy Infrastructure to Staging
on:
  - pull_request
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5
        with:
          node-version-file: ./iac/package.json
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: sapientone-staging
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
